MinerPath:
MinerArgs:
NoDevFee: true
Sender:
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
  Address:
  Password:
  DisplayedName: Polly
Subscribes:
-

Profiles:
- Bad:
  -
  Tolerance:
    DurationMinutes: 0
    Good:
    -
  Action:

StuckProfile:
  ToleranceMinutes: 5
  Action:

QuickExitProfile:
  ToleranceMinutes: 1
  Action:
    
PublicIpCheckMinutes: 30

MaxLogLines: 50
